REQUIRE std.fth

BANK@
LOWRAM BANK!
CREATE BASE-DEPTH 1 CELLS ALLOT
CREATE ACTUAL-DEPTH 1 CELLS ALLOT
CREATE ACTUAL-STACK 10 CELLS ALLOT
BANK!

: PRINT-ACTUAL
  ." Actual stack:" CR
  ACTUAL-DEPTH @ IF
    ACTUAL-STACK ACTUAL-DEPTH @ CELLS EACH ?DO
      I @ .
    1 CELLS +LOOP
  ELSE
    ." {empty}" CR
  THEN
;

( c-addr count -- )
: .TEST-ERROR
  CR PRINT-LINE ." TEST ERROR: " TYPE CR PRINT-ACTUAL ABORT
;

( count addr -- )
: !CELLS
  SWAP CELLS EACH ?DO
    I !
  1 CELLS +LOOP ;

: T{ DEPTH BASE-DEPTH ! ; LABEL _TEST_BEGIN
: -> DEPTH
     DUP ACTUAL-DEPTH !
     BASE-DEPTH @ - ACTUAL-STACK !CELLS ;
LABEL _TEST_EXPECTED
: }T DEPTH ACTUAL-DEPTH @ <> IF S" Unequal stacks." .TEST-ERROR THEN
     DEPTH BASE-DEPTH @ - CELLS ACTUAL-STACK + ACTUAL-STACK ?DO
       I @ <> IF UNLOOP S" Unexpected value." .TEST-ERROR THEN
     1 CELLS +LOOP ;
LABEL _TEST_END

