REQUIRE state-machine.fth

<STATES
  STATE: LEVEL-INIT
  STATE: LEVEL-MIDDLE
  STATE: LEVEL-DONE
STATES>COUNT: NUM-LEVEL-STATES

NUM-LEVEL-STATES
<STATE-MACHINE LEVEL-FSM
  LEVEL-INIT STATE-BEHAVIOR:
    \ Level init behavior.
    ." Level init!" CR
    LEVEL-MIDDLE STATE!
  ;
  LEVEL-MIDDLE STATE-BEHAVIOR:
    \ Level init behavior.
    ." Level mid!" CR
    LEVEL-DONE STATE!
  ;
  LEVEL-DONE STATE-BEHAVIOR:
    ." Level done!" CR
    \ Other behavior.
    \ Final state so never changes.
    DROP
  ;
STATE-MACHINE>

BANK@
LOWRAM BANK!
CREATE LEVEL-STATE 1 CELLS ALLOT
BANK!

LEVEL-INIT LEVEL-STATE !
LEVEL-STATE LEVEL-FSM
LEVEL-STATE LEVEL-FSM
LEVEL-STATE LEVEL-FSM

